config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users do
    member do
      get "followers" => "followers#index"
      get "following" => "following#index"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index, :show] do
    resources :lessons, only: :create
  end
  resources :lessons, only: [:show, :update, :destroy]
  resources :words, only: :index
  namespace :admin do
    root "users#index"
    resources :users, only: [:index, :destroy]
    resources :categories do
      resources :words, except: [:index, :show]
    end
    resources :lessons, only: [:index, :destroy]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @user_following = current_user.following.size
      @user_followers = current_user.followers.size
      @activities = Activity.feed(current_user.id).recent
        .paginate page: params[:page], per_page: Settings.per_page
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/about.html.erb
<title><%= t "about" %></title> 
<h1><%= t "about" %></h1>
<p><%= t "abouts" %></p>

app/views/static_pages/contact.html.erb
<title><%= t "contact" %></title>
<%= t "contact" %>
<p> <%= t "contacts" %> </p>

app/views/static_pages/help.html.erb
<title><%= t "help" %></title>
<h1><%= t "help" %></h1>
<p><%= t "helps" %></p>

app/views/static_pages/home.html.erb
<title><%= t "home" %></title>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-3">
      <section>
        <%= render "shared/user_info" %>
      </section>
      <section>
      	<%= render "shared/stats" %>
      </section>
      <section>
        <%= render "shared/menu_learn" %>
      </section>
      <% if current_user.admin %>
        <section>
          <%= render "shared/menu_admin" %>
        </section>
      <% end %>
    </aside>
    <div class="col-md-9">
      <div class="row btn-action-home">
        <div class="col-md-4 col-md-offset-1">
          <%= link_to t(:words), words_path,
            class: "btn btn-info btn-block" %>
        </div>
        <div class="col-md-4 col-md-offset-2">
          <%= link_to t(:lessons), categories_path,
            class: "btn btn-primary btn-block" %>
        </div>
      </div>
      <hr/>
      <div class="col-md-8">
        <% if @activities.any? %>
          <h3><%= t "activities" %></h3>
          <ol class="activities">
            <%= render @activities %>
          </ol>
          <%= will_paginate @activities %>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t "homes" %></h1>
    <%= link_to t(:signup), new_user_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>