config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users do
    member do
      get "followers" => "followers#index"
      get "following" => "following#index"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index, :show] do
    resources :lessons, only: :create
  end
  resources :lessons, only: [:show, :update, :destroy]
  resources :words, only: :index
  namespace :admin do
    root "users#index"
    resources :users, only: [:index, :destroy]
    resources :categories do
      resources :words, except: [:index, :show]
    end
    resources :lessons, only: [:index, :destroy]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t :count_error_form, count: object.errors.count %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu_admin.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t :managements %></h3>
  </div>
  <div class="list-group">
    <%= link_to t(:category), admin_categories_path, class: "list-group-item" %>
    <%= link_to t(:lessons), admin_lessons_path, class: "list-group-item" %>
    <%= link_to t(:users), admin_users_path, class: "list-group-item" %>
  </div>
</div>

app/views/shared/_menu_learn.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t :learns %></h3>
  </div>
  <div class="list-group">
    <%= link_to t(:category), categories_path, class: "list-group-item" %>
    <%= link_to t(:words), words_path, class: "list-group-item" %>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="btn-group btn-group-justified">
  <%= link_to @user_following.to_s << t("follow.following"), following_user_path(@user),
    class: "btn btn-default" %>
  <%= link_to @user_followers.to_s << t("follow.followers"), followers_user_path(@user),
    class: "btn btn-default" %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for current_user, current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(:view_profile), current_user %></span>