config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users do
    member do
      get "followers" => "followers#index"
      get "following" => "following#index"
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index, :show] do
    resources :lessons, only: :create
  end
  resources :lessons, only: [:show, :update, :destroy]
  resources :words, only: :index
  namespace :admin do
    root "users#index"
    resources :users, only: [:index, :destroy]
    resources :categories do
      resources :words, except: [:index, :show]
    end
    resources :lessons, only: [:index, :destroy]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  scope :recent, ->{order created_at: :desc}

  validates :name, presence: true, length: {maximum: 100},
    uniqueness: {case_sensitive: false}
  validates :description, presence: true, length: {maximum: 300}

  def base_resource
    self.name
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_category, except: [:index, :new, :create]

  def index
    @categories = Category.recent.paginate page: params[:page],
      per_page: Settings.category_page
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      make_activity t("activity.create_category"), @category
      flash[:success] = t "message.create_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "message.invalid_input"
      render :new
    end
  end

  def show
    @words = @category.words.recent.includes(:answers)
      .correct.references(:answers).paginate page: params[:page],
        per_page: Settings.category_page
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      make_activity t("activity.update_category"), @category
      flash[:success] = t "message.update_success"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      make_activity t("activity.destroy_category"), @category
      flash[:success] = t "message.delete_success"
    else
      flash[:danger] = t "message.delete_fail"
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit :name, :description
  end

  def load_category
    @category = Category.find_by id: params[:id]
    if @category.nil?
      flash[:danger] = t "category.not_found"
      redirect_to admin_categories_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.includes(:words).paginate page: params[:page],
      per_page: Settings.category_page
  end

  def show
    @category = Category.find_by id: params[:id]
    if @category.nil?
      flash[:danger] = t "category.not_found"
      redirect_to root_path
    else
      @lessons = @category.lessons.of_user(current_user.id).recent
        .paginate page: params[:page], per_page: Settings.category_page
    end
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td class="category-name">
    <%= category.name %>
  </td>
  <td class="category-description">
    <%= category.description %>
  </td>
  <td class="col-actions text-right">
    <%= link_to [:admin, category], class: "btn btn-info btn-xs" do %>
      <span class="glyphicon glyphicon-eye-open"></span> <%= t :details %>
    <% end %>
    <%= link_to [:edit, :admin, category],
      class: "btn btn-default btn-xs" do %>
      <span class="glyphicon glyphicon-edit"></span>
      <%= t :edit %>
    <% end %>
    <%= link_to admin_category_path(category), method: :delete,
      class: "btn btn-danger btn-xs", data: {confirm: t(:you_sure)} do %>
      <span class="glyphicon glyphicon-remove"></span> <%= t :delete %>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_category_form.html.erb
<%= form_for [:admin, category] do |f| %>
<%= render "/shared/error_messages", object: category %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <%= f.submit t(:submit), class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<title><%= t"edit" %></title>
<h1><%= t :edit_category %></h1>
<%= render "category_form", category: @category %>

app/views/admin/categories/index.html.erb
<title><%= t "category" %></title>
<h3><%= t :categories %></h3>
<hr/>
<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <%= link_to new_admin_category_path, class: "btn btn-primary" do %>
        <span class="glyphicon glyphicon-plus-sign"></span>
        <%= t :create_new %>
      <% end %>
    </div>
  </div>
</div>
<br/>
<% if @categories.any? %>
  <table class="table table-hover">
    <tr>
      <th><%= t "category.name" %></th>
      <th><%= t "category.description" %></th>
      <th></th>
    </tr>
    <%= render @categories %>
  </table>
  <div class="text-center">
    <%= will_paginate %>
  </div>
<% else %>
  <%= t :no_items_found %>
<% end %>

app/views/admin/categories/new.html.erb
<title><%= t "category" %></title>
<% provide t(:new_category) %>
<% provide :button_text, t(:create_category) %>
<h1><%= t :new_category %></h1>
<%= render "category_form", category: @category %>

app/views/admin/categories/show.html.erb
<title><%= @category.name %></title>
<h2><%= @category.name %></h2>
<p><%= @category.description %></p>
<div class="row">
  <div class="col-md-12">
    <div class="pull-right">
      <%= link_to new_admin_category_word_path(@category),
        class: "btn btn-primary" do %>
        <span class="glyphicon glyphicon-plus-sign"></span>
        <%= t :create_a_word %>
      <% end %>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t :words %></h3>
  </div>
  <% if @words.any? %>
    <%= render @words %>
    <div class="text-center">
      <%= will_paginate @words %>
    </div>
  <% else %>
    <%= t :no_items_found %>
  <% end %>
</div>